package com.kora.ecommerce.order.application.payment;

public enum PaymentResultEventFailure {
    EMPTY_PAYLOAD,
    MALFORMED_JSON,
    MISSING_EVENT_ID,
    MALFORMED_EVENT_ID,
    MISSING_EVENT_TYPE,
    UNSUPPORTED_EVENT_TYPE,
    MISSING_EVENT_VERSION,
    UNSUPPORTED_EVENT_VERSION,
    MISSING_AGGREGATE_ID,
    MALFORMED_AGGREGATE_ID,
    MISSING_OCCURRED_AT,
    MALFORMED_OCCURRED_AT,
    MISSING_DATA,
    MISSING_ORDER_ID,
    MALFORMED_ORDER_ID,
    MISSING_PAYMENT_ID,
    MALFORMED_PAYMENT_ID,
    ORDER_ID_MISMATCH
}
